version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - xbee_listener

  xbee_listener:
    build:
      context: .
      dockerfile: Dockerfile.xbee
    restart: always
